# Generated by Django 3.2 on 2021-11-07 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_get_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='call_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
