# Generated by Django 3.2 on 2021-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apicall_call_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
