# Generated by Django 3.2 on 2021-11-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_currency_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
    ]
